<html>
<head>
    <title>A I M S</title>
    <link rel="shortcut icon" type="image/png" href="https://cdn0.iconfinder.com/data/icons/tiny-icons-1/100/tiny-15-512.png">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/buttons.css">
    <link rel="stylesheet" href="/static/css/photos.css">
    <link rel="stylesheet" href="/static/css/text.css">
    <script type="text/javascript" src="/static/javascript/js.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="/static/css/menu.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <#import "parts/footer.ftlh" as footer>
    <#import "parts/menu.ftlh" as menu>
    <#import "parts/elements.ftlh" as elements>

</head>
<body>

    <@menu.customMenu menuElements slideMenuElements/>

    <!-- First Parallax Image with Text -->
    <div class="parallax big-img-aims w3-display-container w3-opacity-min" id="home">
        <div class="w3-display-middle" style="white-space:nowrap;">
            <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">WHAT IS AIM</span>
        </div>
    </div>

    <!-- Definition of AIM container-->
    <div class="w3-content w3-container w3-padding-32" id="about">
        <h3 class="w3-center w3-black ">AIM IS</h3>
        <p class="w3-center article"><em>Dream</em></p>
        <p class="article-text">
            A goal is an idea of the future or desired result that a person or a group of people envision, plan and commit
            to achieving. People endeavour to reach goals within a finite time by setting deadlines. A goal is roughly
            similar to a purpose or aim, the anticipated result which guides reaction, or an end, which is an object,
            either a physical object or an abstract object, that has intrinsic value.
        </p>
        <div class="w3-row">
            <div class="w3-col m6 w3-center w3-padding-large">
                <img src= "https://3.bp.blogspot.com/-o6v3A_fmflA/WAoc16_1klI/AAAAAAAAAE4/InAvp8WNspIhIhd8-Jw5SEDiL83zSQPBQCLcB/s1600/aim%2B1.png"
                     class="big-img-small-smart w3-round w3-image w3-opacity w3-hover-opacity-off"
                     onclick="onClick(this)" width="100%">
                <p>
                    <b>Achieve your dream</b>
                </p>
                <br>
            </div>

            <!-- Hide this text on small devices -->
            <div class="w3-col m6 w3-hide-small w3-padding-large">
                <p class="article-text">
                    Achieving personal goals
                    Achieving complex and difficult goals requires focus, long-term diligence and effort (see Goal pursuit).
                    Success in any field requires forgoing excuses and justifications for poor performance or lack of
                    adequate planning; in short, success requires emotional maturity. The measure of belief that people
                    have in their ability to achieve a personal goal also affects that achievement.
                </p>
            </div>
        </div>
        <p class="article-text">
            Long-term achievements rely on short-term achievements. Emotional control over the small moments of the
            single day makes a big difference in the long term.

            Personal goal achievement and happiness
            There has been a lot of research conducted looking at the link between achieving desired goals, changes
            to self-efficacy and integrity and ultimately changes to subjective well-being. Goal efficacy
            refers to how likely an individual is to succeed in achieving their goal. Goal integrity refers to how
            consistent one's goals are with core aspects of the self. Research has shown that a focus on goal
            efficacy is associated with well-being factor happiness (subjective well-being) and goal integrity is
            associated with the well-being factor meaning (psychology). Multiple studies have shown the link
            between achieving long-term goals and changes in subjective well-being; most research shows that
            achieving goals that hold personal meaning to an individual increases feelings of subjective well-being.
        </p>
    </div>

    <!-- Second Parallax Image with Portfolio Text -->
    <div class="parallax big-img-10k-hours w3-display-container w3-opacity-min" id="home">
        <div class="w3-display-middle" style="white-space:nowrap;">
            <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">10K H</span>
        </div>
    </div>

    <!-- Definition of AIM container-->
    <div class="w3-content w3-container w3-padding-32" id="definition">
        <h3 class="w3-center w3-black ">10,000 hours </h3>
        <p class="w3-center article"><em>Outliers: The Story of Success</em></p>
        <p class="article-text">
            What does it take to become an expert or master performer in a given field? 10,000 hours of practice.
            It’s a common rule of thumb, popularized by Malcom Gladwell in his bestseller Outliers: The Story of Success.
            It’s catchy, easy to remember, and – more or less – completely false.

            We’re debunking the 10,000 hour rule and taking a look at proven ways to practice your way to mastery.
        </p>
        <div class="w3-row">
            <div class="w3-col m6 w3-center w3-padding-large">

                <img src="https://scontent.fdnk1-2.fna.fbcdn.net/v/t1.0-9/p960x960/50395137_596294490807772_1256547962968866816_o.png?_nc_cat=111&_nc_ohc=UgoNRZFZNI0AQm7g4wQR69icsTAxnUE7ho-bKLuQO9hmhx_4-TcSnfSVA&_nc_ht=scontent.fdnk1-2.fna&oh=fdea51fef4b6e7e1833abc68d2b75774&oe=5EB04FE0"
                     class="big-img-small-smart w3-round w3-image w3-opacity w3-hover-opacity-off"
                     onclick="onClick(this)" width="100%">
                <p>
                    <b>10,000 hours</b>
                </p>
                <br>
            </div>

            <!-- Hide this text on small devices -->
            <div class="w3-col m6 w3-hide-small w3-padding-large">
                <p class="article-text">
                    In looking at lots of different areas, from computing, business through sport, to music there seems
                    to be a magic number of 10,000 – the number of hours ‘masters’ of their chosen area have put in.
                    Meaningful work makes you want to ‘put in the hours’.  Sociologist, Louise Farkas studied the family
                    tree of many immigrants and found that their offspring became professionals.  She put it down to the
                    fact that it was because of their humble origins not inspite of it that they did well – i.e. they had
                    been raised in a family where hard work was valued and practiced. <br>
                </p>
            </div>

            <div class="w3-center">
                <a href="/ten_thousand_hours_aim#create"> <button class="btn btn1 w3-button w3-padding-large" >Create 10k h aim</button></a>
            </div>
        </div>
    </div>

    <!-- First Parallax Image with Text -->
    <div class="parallax big-img-smart w3-display-container w3-opacity-min" id="first">
        <div class="w3-display-middle" style="white-space:nowrap;">
            <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">S.M.A.R.T</span>
        </div>
    </div>

    <div class="w3-content w3-container w3-padding-32" id="about">
        <h3 class="w3-center w3-black ">S.M.A.R.T </h3>
        <p class="w3-center article"><em>Smart Criteria</em></p>
        <p class="article-text">
            SMART is a mnemonic/acronym, giving criteria to guide in the setting of objectives, for example in project
            management, employee-performance management and personal development. The letters S and M generally mean
            specific and measurable. Possibly the most common version has the remaining letters referring to achievable
            (or attainable), relevant, and time-bound. However, the term's inventor had a slightly different version and
            the letters have meant different things to different authors, as described below. Additional letters have
            been added by some authors.
        </p>
        <div class="w3-row">
            <div class="w3-col m6 w3-center w3-padding-large">
                <img src="https://www.thebalancesmb.com/thmb/5B7wGRFmXySMaXXh9ZhOhw11v2w=/950x0/smart-goal-examples-2951827_final-5b6887cc46e0fb0050aa0bc9.png"
                     class="big-img-small-smart w3-round w3-image w3-opacity w3-hover-opacity-off"
                     onclick="onClick(this)" alt="Photo of Me" width="100%">
                <p>
                    <b>S.M.A.R.T</b>
                </p>
                <br>
            </div>

            <!-- Hide this text on small devices -->
            <div class="w3-col m6 w3-hide-small w3-padding-large">
                <p class="article-text">
                    The November 1981 issue of Management Review contained a paper by George T. Doran
                    called There's a S.M.A.R.T. way to write management's goals and objectives.
                    It discussed the importance of objectives and the difficulty of setting them.

                    Ideally speaking, each corporate, department, and section objective should be:

                    Specific – target a specific area for improvement.
                    Measurable – quantify or at least suggest an indicator of progress.
                    Assignable – specify who will do it.

                </p>
            </div>
            <p class="article-text">
                Realistic – state what results can realistically be achieved, given available resources.
                Time-related – specify when the result(s) can be achieved.
                Notice that these criteria don't say that all objectives must be quantified on all levels of
                management. In certain situations it is not realistic to attempt quantification, particularly
                in staff middle-management positions. Practicing managers and corporations can lose the benefit of a
                more abstract objective in order to gain quantification. It is the combination of the objective and
                its action plan that is really important. Therefore serious management should focus on these twins
                and not just the objective.

                — George T. Doran, There's a S.M.A.R.T. way to write management's goals and objectives
            </p>
        </div>

        <div class="w3-center">
            <a href="/main_aim#create"> <button class="btn btn2 w3-button w3-padding-large" >Create SMART aim</button></a>
        </div>
    </div>

    <div class="parallax big-img-goals-plans w3-display-container w3-opacity-min" id="last">
    </div>

    <!-- Footer -->
    <@footer.footer/>

</body>
</html>