<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>D e t a i l s</title>
    <link rel="shortcut icon" type="image/png" href="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Group_font_awesome.svg/1024px-Group_font_awesome.svg.png">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/buttons.css">
    <script type="text/javascript" src="/static/javascript/js.js"></script>
    <script type="text/javascript" src="/static/javascript/validators.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="/static/css/menu.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <#import "parts/footer.ftlh" as footer>
    <#import "parts/elements.ftlh" as elements>
    <#import "parts/charst.ftlh" as charts>
    <#import "parts/details.ftlh" as details>
    <#import "parts/timeMacros.ftlh" as time>
    <#import "parts/popups.ftlh" as popups>
    <#import "parts/menu.ftlh" as menu>

</head>
<body>

    <style>
        .fa{margin-right: 5px;}
    </style>

    <@menu.customMenu menuElements slideMenuElements/>

    <div class="parallax big-img-macro-raindrop w3-display-container w3-opacity-min" id="home">
        <div class="w3-display-middle" style="white-space:nowrap;">
            <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">Details</span>
        </div>
    </div>

    <div class="w3-content w3-container w3-padding-32" id="details">
        <#if aim.aimState == "ACHIEVED">
            <h3 class="w3-center w3-black" style="background-color: #616161!important;">${aim.title!''}
                <i class="fa fa-check" style="color: #2E9267;" title="Achieved!"></i>
            </h3>
        <#else>
            <h3 class="w3-center w3-black" style="background-color: #616161!important;">${aim.title!''}</h3>
        </#if>
        <p class="w3-center article"><em>${aim.description!''}</em></p>

    <#--Aim main details-->
        <div class="w3-row" id="main-details" style="padding: 12px 24px!important">
            <div class="w3-col m6 w3-center w3-padding-large">
                <@details.userDetails user=aim.user/>
            </div>
            <div class="w3-col m6 w3-hide-small w3-center">
                <@details.aimDetails aim=aim/>
            </div>
        </div>

        <div class="w3-center">
            <h3 class="w3-center" style="color: #777!important;">Time logging</h3>
        </div>

        <div class="w3-row">
            <#--Left side of dib-->
            <div class="w3-col m6 w3-center w3-padding-large">
                <@charts.largeBarChart loggedTime=lastWeekLoggedTime/>
                <@popups.details></@popups.details>
                <br>
                <a href="/tenKAimTimeAnalyzer/${aim.id}">
                    <button class="btn btn1 w3-button w3-padding-large">Analyzer</button>
                </a>
            </div>
            <#--Rigth side of dib-->
            <div class="w3-col m6 w3-hide-small w3-center">
                <form action="/tenKHoursAimDetails/saveDetails" method="get">
                   <@time.timeLogging aim/>
                </form>
            </div>
        </div>

        <div class="w3-center">
            <a href="/ten_thousand_hours_aim#aimsTable">
                <button class="btn btn2 w3-button w3-padding-large">Back to aims</button>
            </a>
        </div>
    </div>

    <div class="parallax big-img-macro-raindrop-small w3-display-container w3-opacity-min" id="home">
        <div class="w3-display-middle" style="white-space:nowrap;">
        </div>
    </div>

    <@footer.footer/>

</body>
</html>
