<html>
<head>
    <title>W e l c o m e</title>
    <link rel="shortcut icon" type="image/png" href="https://cdn.onlinewebfonts.com/svg/img_51582.png">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/buttons.css">
    <link rel="stylesheet" href="/static/css/text.css">
    <link rel="stylesheet" href="/static/css/menu.css">

    <script type="text/javascript" src="/static/javascript/js.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <div id="home" class="w3-top">
        <div class="w3-bar" id="myNavBar">
            <a href="/" class="w3-bar-item w3-button"><i class="fa fa-home"></i> HOME</a>
            <a href="/events" class="w3-bar-item w3-button"><i class="fa fa-calendar"></i> EVENTS</a>
            <a href="#about" class="w3-bar-item w3-button"><i class="fa fa-book"></i> ABOUT</a>
            <a href="#footer" class="w3-bar-item w3-button"><i class="fa fa-chevron-down"></i> DOWN</a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-chevron-up"></i> UP</a>
            <a href="/login" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-red"><i class="fa fa-sign-in"></i></a>
            <a href="/userProfile" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-red"><i class="fa fa-user"></i></a>
        </div>

        <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium">
            <a href="/" class="w3-bar-item w3-button w3-right w3-hover-red"><i class="fa fa-home"></i></a>
            <a href="#" class="w3-bar-item w3-button w3-right w3-hover-red"><i class="fa fa-chevron-up"></i>UP</a>
            <a href="/login" class="w3-bar-item w3-button w3-right w3-hover-red"><i class="fa fa-sign-in"></i></a>
        </div>
    </div>

    <div class="parallax big-img-greeting-1 w3-display-container w3-opacity-min" id="home">
        <div class="w3-display-middle" style="white-space:nowrap;">
            <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">Event Management System</span>
        </div>
    </div>

    <div class="w3-content w3-container w3-padding-32" id="choose-preferences">
        <div class="w3-center w3-row">
            <form action="/userPreferences/save" method="post" style="margin: 30px 10px 10px">
                <#list tags?keys as eventType>
                    <#if eventType?has_content && tags[eventType]?has_content>
                        <br>
                        ${eventType}
                        <#list tags[eventType] as tag>
                            <div>
                                <label>
                                    <#if user.firstLogin>
                                        <input type="checkbox" name="${tag.name}">
                                        ${tag.description}
                                    <#else>
                                        <input type="checkbox" name="${tag.name}"
                                                ${user.tags?seq_contains(tag)?string("checked", "")}>
                                        ${tag.description}
                                    </#if>
                                </label>
                            </div>
                        </#list>
                    </#if>
                </#list>
                <br>
                <input type="hidden" value="${user.id}" name="user">
                <input type="hidden" value="${_csrf.token}" name="_csrf">
                <button type="submit" class="small-btn btn2 w3-button w3-padding-large">Save</button>
            </form>
        </div>
    </div>

    <div class="parallax big-img-greeting-small w3-display-container w3-opacity-min" id="footer">
    </div>

    <footer class="w3-center w3-black w3-padding-32 w3-opacity w3-hover-opacity-off">
        <a href="#home" class="" style="text-decoration: none; color: #ABADAA;"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
        <div class="w3-xlarge w3-section">
            <a href="" target="_blank"
               class="fa fa-git w3-hover-opacity" style="text-decoration: none;"></a>
        </div>
    </footer>
</body>
</html>